# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
services:
- postgres:14.5
variables:
  POSTGRES_USER: phoenix
  POSTGRES_DB: phoenix
  POSTGRES_HOST_AUTH_METHOD: trust
  LICENSE_FINDER_CLI_OPTS: '--recursive'
stages:
- test
- publish

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml  
- template: Security/License-Scanning.gitlab-ci.yml

migrate-and-test:
  stage: test
  variables:
    DATABASE_URL: postgres://phoenix:phoenix@postgres:5432/phoenix
    H_ORIGIN: localhost:5000
  image:
    name: ruby:2.7.2
  script:
  - gem install bundler
  - gem install rails
  - bundle install
  - rails db:migrate
  - rails server -d
  - sleep 20
  - kill $(cat tmp/pids/server.pid)



docker-nightly:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}:nightly" --build-arg GIT_TAG=nightly
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


docker-prod:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" --build-arg GIT_TAG=${CI_COMMIT_TAG}
  rules:
  - if: $CI_COMMIT_TAG
